@startuml
设备 -> 打印机: 0.usb连接
小程序 -> 设备: 1.连接设备wifi\n2.将设备接入具备\n   广域网连接的已有wifi网络
小程序 -> 云服务器: 3.将设备连接的打印机\n的网络地址绑定至账户
设备 -> 云服务器: 4.连接云服务器网络

小程序 -> 云服务器: 发送打印内容
云服务器 -> 云服务器: 处理打印内容
云服务器 -> 设备: 调用账户绑定的打印机网络地址进行打印
@enduml